version: '3'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    restart: unless-stopped
    ports:
      # SSH Honeypot Port (using standard SSH port)
      - "22:2222"
      # Telnet Honeypot Port
      - "23:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
      - cowrie-downloads:/cowrie/cowrie-git/downloads
      - cowrie-log:/cowrie/cowrie-git/var/log/cowrie
    environment:
      - COWRIE_TELNET_ENABLED=yes
      - TZ=UTC
    networks:
      - honeypot-network

  cowrie-irc-bot:
    build: ./cowrie_irc_bot
    container_name: cowrie-irc-bot
    restart: unless-stopped
    depends_on:
      - cowrie
    volumes:
      - cowrie-log:/var/log/cowrie:ro
      - cowrie-irc-config:/etc/cowrie-irc-bot
      - cowrie-irc-logs:/var/log/cowrie-irc-bot
    environment:
      - TZ=UTC
    networks:
      - honeypot-network
    # Use only supported command-line arguments
    command: --config /etc/cowrie-irc-bot/config.json

volumes:
  cowrie-etc:
  cowrie-var:
  cowrie-downloads:
  cowrie-log:
  cowrie-irc-config:
  cowrie-irc-logs:

networks:
  honeypot-network: