version: '3'

services:
  cowrie-honeypot:
    image: cowrie/cowrie
    container_name: cowrie-honeypot
    restart: unless-stopped
    volumes:
      - ./honeypot-data:/cowrie/cowrie-git/var
    ports:
      - "2222:2222"
      - "2223:2223"
    environment:
      - TZ=UTC  # Set timezone as needed
    
  cowrie-irc-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: cowrie-irc-bot:latest
    container_name: cowrie-irc-bot
    restart: unless-stopped
    volumes:
      - ./honeypot-data/log/cowrie:/var/log/cowrie:ro
      - ./config:/etc/cowrie-irc-bot:ro
      - ./logs:/var/log/cowrie-irc-bot
    environment:
      - TZ=UTC  # Set timezone as needed
    # If you need to use a custom configuration file
    command: --config /etc/cowrie-irc-bot/config.json
    depends_on:
      - cowrie-honeypot