version: '3'

services:
  cowrie-irc-bot:
    build: .
    container_name: cowrie-irc-bot
    restart: unless-stopped
    volumes:
      - /var/log/cowrie:/var/log/cowrie:ro
      - ./config:/etc/cowrie-irc-bot
      - ./logs:/var/log/cowrie-irc-bot
    environment:
      - TZ=UTC  # Set timezone as needed
    # If you need to use a custom configuration file
    command: --config /etc/cowrie-irc-bot/config.json